/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VinculosRouteImport } from './routes/vinculos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RotacoesRouteImport } from './routes/rotacoes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PreceptoresRouteImport } from './routes/preceptores'
import { Route as HospitaisRouteImport } from './routes/hospitais'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CargaHorariaRouteImport } from './routes/carga-horaria'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const VinculosRoute = VinculosRouteImport.update({
  id: '/vinculos',
  path: '/vinculos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RotacoesRoute = RotacoesRouteImport.update({
  id: '/rotacoes',
  path: '/rotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PreceptoresRoute = PreceptoresRouteImport.update({
  id: '/preceptores',
  path: '/preceptores',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitaisRoute = HospitaisRouteImport.update({
  id: '/hospitais',
  path: '/hospitais',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CargaHorariaRoute = CargaHorariaRouteImport.update({
  id: '/carga-horaria',
  path: '/carga-horaria',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRoute
  '/atividades': typeof AtividadesRoute
  '/carga-horaria': typeof CargaHorariaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/hospitais': typeof HospitaisRoute
  '/preceptores': typeof PreceptoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/rotacoes': typeof RotacoesRoute
  '/usuarios': typeof UsuariosRoute
  '/vinculos': typeof VinculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRoute
  '/atividades': typeof AtividadesRoute
  '/carga-horaria': typeof CargaHorariaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/hospitais': typeof HospitaisRoute
  '/preceptores': typeof PreceptoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/rotacoes': typeof RotacoesRoute
  '/usuarios': typeof UsuariosRoute
  '/vinculos': typeof VinculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRoute
  '/atividades': typeof AtividadesRoute
  '/carga-horaria': typeof CargaHorariaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/hospitais': typeof HospitaisRoute
  '/preceptores': typeof PreceptoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/rotacoes': typeof RotacoesRoute
  '/usuarios': typeof UsuariosRoute
  '/vinculos': typeof VinculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/alunos'
    | '/atividades'
    | '/carga-horaria'
    | '/configuracoes'
    | '/dashboard'
    | '/hospitais'
    | '/preceptores'
    | '/relatorios'
    | '/rotacoes'
    | '/usuarios'
    | '/vinculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/alunos'
    | '/atividades'
    | '/carga-horaria'
    | '/configuracoes'
    | '/dashboard'
    | '/hospitais'
    | '/preceptores'
    | '/relatorios'
    | '/rotacoes'
    | '/usuarios'
    | '/vinculos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/alunos'
    | '/atividades'
    | '/carga-horaria'
    | '/configuracoes'
    | '/dashboard'
    | '/hospitais'
    | '/preceptores'
    | '/relatorios'
    | '/rotacoes'
    | '/usuarios'
    | '/vinculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AlunosRoute: typeof AlunosRoute
  AtividadesRoute: typeof AtividadesRoute
  CargaHorariaRoute: typeof CargaHorariaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  HospitaisRoute: typeof HospitaisRoute
  PreceptoresRoute: typeof PreceptoresRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RotacoesRoute: typeof RotacoesRoute
  UsuariosRoute: typeof UsuariosRoute
  VinculosRoute: typeof VinculosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vinculos': {
      id: '/vinculos'
      path: '/vinculos'
      fullPath: '/vinculos'
      preLoaderRoute: typeof VinculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotacoes': {
      id: '/rotacoes'
      path: '/rotacoes'
      fullPath: '/rotacoes'
      preLoaderRoute: typeof RotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preceptores': {
      id: '/preceptores'
      path: '/preceptores'
      fullPath: '/preceptores'
      preLoaderRoute: typeof PreceptoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitais': {
      id: '/hospitais'
      path: '/hospitais'
      fullPath: '/hospitais'
      preLoaderRoute: typeof HospitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carga-horaria': {
      id: '/carga-horaria'
      path: '/carga-horaria'
      fullPath: '/carga-horaria'
      preLoaderRoute: typeof CargaHorariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AlunosRoute: AlunosRoute,
  AtividadesRoute: AtividadesRoute,
  CargaHorariaRoute: CargaHorariaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  HospitaisRoute: HospitaisRoute,
  PreceptoresRoute: PreceptoresRoute,
  RelatoriosRoute: RelatoriosRoute,
  RotacoesRoute: RotacoesRoute,
  UsuariosRoute: UsuariosRoute,
  VinculosRoute: VinculosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
