-- Add preceptor_id column to alunos
ALTER TABLE public.alunos
  ADD COLUMN IF NOT EXISTS preceptor_id uuid REFERENCES public.preceptores(id) ON DELETE SET NULL;

-- Unique index for case-insensitive nome dedupe
CREATE UNIQUE INDEX IF NOT EXISTS preceptores_nome_lower_uniq
  ON public.preceptores (lower(nome));

-- Seed 228 preceptores (idempotent)
INSERT INTO public.preceptores (nome) VALUES
  ('Amanda Oliveira de Carvalho'),
  ('Amine Hardmann Icó Santana'),
  ('Ana Carla Marçal Caxeado Sapori'),
  ('Carmem Maria Brito Achy'),
  ('Carolina de Almeida Pimenta Pinheiro'),
  ('Carolina Micol Leite Oliveira Menezes'),
  ('Christiane de Carvalho Silva'),
  ('Cláudia Almeida Rebelo'),
  ('Cristina Damasceno Correia'),
  ('Dalvio Freitas de Matos'),
  ('Daniela Pereira Matos'),
  ('Elisangela Lemos Rodrigues'),
  ('Gabriele Macedo Mascarenhas'),
  ('Geovana Santos Sá'),
  ('Herry Vieria Zuza'),
  ('Jeane Rodrigues de Andrade'),
  ('Jorge de Oliveira Santos Neto'),
  ('Júlia Larissa Melo de Jesus'),
  ('Larissa Ohana Santos Rodrigues de Araújo'),
  ('Luis Antônio Bahiana Cruz'),
  ('Luiz Alberto Ribeiro Chagas'),
  ('Priscila Dias Afonso'),
  ('Rafaela Moitinho Moura'),
  ('Talitha Maria Mascarenhas de Oliveira'),
  ('Thiago Carvalho de Sousa'),
  ('Verônica Rita Pinto de Araújo'),
  ('Wilson Andrade Carvalho Junior'),
  ('Adilson Machado Couto Filho'),
  ('Aline Fernandes Mangabeira'),
  ('Alvaro da Silva Oliveira Junior'),
  ('Ana Celia Diniz Cabral Barbosa Romeo'),
  ('Antônio Carlos Assunção Neto'),
  ('Antônio Carlos Pinto Valadares Filho'),
  ('Augusto Virgilio Fraga de Gaffga'),
  ('Bruna Santos Freitas'),
  ('Carlos Eduardo Moreira Guedine Júnior'),
  ('Eduardo Doria Pinto Rodrigues da Costa'),
  ('Eduardo Silva Farias'),
  ('FABIANO SCHITINI ESPINHEIRA'),
  ('FELIPE PINHO E ALBUQUERQUE E SILVA'),
  ('Filipe Ponte de Souza'),
  ('Francisco Rodrigo Pamplona de Lima'),
  ('Gabriela Gandarela do Espírito Santo Dourado'),
  ('Geraldo Henrique Behrens de Araújo Góes'),
  ('Gil Kléber Leão da Cruz'),
  ('Guilherme Cabral Tanuri Marques'),
  ('Guilherme Midlej Menezes'),
  ('Gustavo Henrique Teles Ferreira'),
  ('Gustavo Lima O''Dwyer'),
  ('Jasiel Oliveira Cunha Neto'),
  ('Joamar Nunes de Melo'),
  ('Joana Carolina Saraiva de Paula Pessoa'),
  ('JOAO RAFAEL LIBORIO ESTRELA'),
  ('João Rafael Silva Santos'),
  ('LEONARDO MARQUES CALAZANS'),
  ('Leonardo Redig Lisboa de Azevedo'),
  ('LEONE KOEHNE RIBEIRO'),
  ('Lilian Cibele Pereira Gomes'),
  ('Luana Portela Mendes Carneiro'),
  ('Lucas Daniel Prado Coutinho'),
  ('Luciano Monteiro Cavalcante'),
  ('Luis Mauricio de Jesus Medeiros'),
  ('Luiz Lanat Pedreira Cerqueria Filho'),
  ('Marcos Vinícius Fernandes Santana'),
  ('Marcus Vinícius Assis da Silva'),
  ('Mariana Cesconetti Peterle'),
  ('MÁRIO FEITOSA FALCÃO'),
  ('Marlizia Claudia Silva Santos'),
  ('Natalie Fernanda Baqueiro Sena'),
  ('NILO JORGE CARVALHO LEÃO BARRETO'),
  ('OLDACH PITOMBO'),
  ('Pablo Tadeu Nunes de Melo'),
  ('Paula Cunha de Azevedo'),
  ('Pedro Ramires Henrique'),
  ('Priscila Filardi de Oliveira'),
  ('Rafael Nascimento de Jesus'),
  ('Rafael Silva Cajazeira'),
  ('RANGEL LELIS PEREIRA'),
  ('Roberta Andrade Moreira de Souza'),
  ('SEBASTIÃO HELDENIR DE MESQUITA JÚNIOR'),
  ('Solon Cavalcanti Guerra'),
  ('Víctor Rocha Sampaio Neiva Rocha'),
  ('Vítor Alvarez Moura Costa'),
  ('Vítor Sávio Melo Costa'),
  ('WENDEL SOUZA KRUSCHEWSKY'),
  ('Yasmin Alves Luz'),
  ('YZA MARIANA CONCEIÇÃO BRITO'),
  ('EVARISTO PEIXOTO OLIVEIRA NETO'),
  ('ALEXANDRE AZEVEDO ZIOMKOWSKY'),
  ('ALEXANDRE VASCONCELOS DE MEIRELES'),
  ('George Wallace Freire Alves'),
  ('ERIC GUSTAVO REGGIANI'),
  ('ENILTON DE SANTANA RIBEIRO DE MATTOS'),
  ('Luís Fernando Weber de Oliveira'),
  ('Gustavo Rabelo Azi'),
  ('DANIELLE MOREIRA DE OLIVEIRA'),
  ('FELIPE BEZERRA ALVES SIEBRA'),
  ('BENEDITA DEBORA DE AGUIAR SANTOS'),
  ('Sérgio Machado Costa'),
  ('Luã Souza Cunha'),
  ('Arthur Rocha Araujo'),
  ('NATHALIA NADIR FERRAZ ARAUJO'),
  ('Cícero Mateus de Castro Silva'),
  ('George Tavares Marins'),
  ('Adriana Aguiar Pepe dos Santos'),
  ('Adriano Augusto teixeira Guimaraes'),
  ('Alexsandro Marques Lourenço'),
  ('Anna Carolina Maia Mata Hermida'),
  ('Antônio Maurício dos Santos Cerqueira Júnior'),
  ('Caio Gomes dos Santos Araujo'),
  ('Caue de Araujo Matte'),
  ('Diego Moreira Arruda'),
  ('Fábio Bulhões'),
  ('Fernando Novaes Sampaio'),
  ('Jackson Marcony Cordeiro Dos Santos'),
  ('Janine Magalhaes Garcia de Oliveira'),
  ('Jaqueline Cardoso da Silva'),
  ('Jener Guerra Macedo'),
  ('Jose Sarmento Cardoso Neto'),
  ('Julia Aslan Ribeiro Chaves'),
  ('Kezia França de Jesus'),
  ('Laiane Santana Carvalho'),
  ('Leonardo Bispo Pires'),
  ('Luciana Jacintho Caleiro'),
  ('Luciano Pimentel Bressy'),
  ('Luis Felipe Almeida Cardoso'),
  ('Marcos Nogueira de Oliveira Rios'),
  ('Mauricio Guitzel Rodrigues'),
  ('Rafique Cardoso Vaz Almeida'),
  ('Ramon Bispo de Jesus'),
  ('Rebeca de Amorim Oliveira'),
  ('Rebeca Lopes Sena Vaz'),
  ('RITA DE CASSIA MARQUES CARDOSO'),
  ('Tamila Pires da Silva'),
  ('Thaissa Torrezini'),
  ('Yuri Freire de Carvalho Espírito Santo'),
  ('Maria Clara Cavalcanti de Araújo'),
  ('Alan de Melo Santos'),
  ('Barbara Alves de Souza Nascimento'),
  ('Carolina Tavares Lambiase'),
  ('Danielle de Gois Lapa'),
  ('Emanuele da Silva Pessoa'),
  ('Fabiane Barbosa de Freitas'),
  ('Felipe Sampaio Rosa Ribeiro'),
  ('Flavio Antonio Maciel dos Santos'),
  ('Isis de Melo Maciel'),
  ('Júlia Maíra Pereira'),
  ('Larissa da Trindade Quintela Santos'),
  ('Marcela Maria Correia Santos'),
  ('Márcia Maria Pedreira da Silveira'),
  ('Maria Eunice Fonseca Leite'),
  ('Mariana Ramos de Oliveira'),
  ('Rosana Moraes da Silva Gomes'),
  ('Tânia Valeria Albuquerque Maia'),
  ('Maria Eduarda Seabra de Oliveira Palmeira'),
  ('Adriana de Carvalho Meira Ivo'),
  ('Aline Maria Monteiro Garrido'),
  ('Ana Teresa Moura de Salles'),
  ('Bianca Pires de Santana'),
  ('Camila Coelho Costa Teixeira'),
  ('Cecília Veiga Malheiros Gil Braz'),
  ('Daniela Teixeira Leal Braga'),
  ('Fabio Zattar Guerios'),
  ('Gabriel Ramos Galvao Reis'),
  ('Igor Assunção Bião Almeida'),
  ('Layce Marques Abrantes'),
  ('Lediane Maniçoba de Moura'),
  ('Leonardo Guimarães Coelho'),
  ('Nimara Grace Cardoso Batista Couto'),
  ('Raísa Muniz de Araújo'),
  ('Roberto Santos Silva'),
  ('Nicole Cruz de Sa'),
  ('Manoela Ribeiro Medeiros'),
  ('Alessandra Freire'),
  ('Carla Maria Ferreira de Sousa'),
  ('Catharine Bittencourt Cunha'),
  ('Edberig Almeida de Araujo'),
  ('Leonardo Ferreira Prado'),
  ('Matheus Cunha Mendonça'),
  ('Nara Borges'),
  ('Vinícius Brito Rocha'),
  ('Júlia Trindade Menezes'),
  ('Adriano Caldeira Silva Morais'),
  ('Lorena Ferreira Oliveira'),
  ('Ana Carolina Viana Mattos'),
  ('Ana Cristina Carneiro dos Reis'),
  ('Andrea Cavalcante'),
  ('Andrea do Prado Queiroz'),
  ('Felipe Carvalho Leão'),
  ('Antonia Calane de Oliveira Santos'),
  ('Carla Emanuella Guimarães da Silva'),
  ('Clarissa Pinto da Rocha Martinelli Pizarro'),
  ('Elis Rebouças da Silva'),
  ('Fernanda Lomanto Sampaio Tavares'),
  ('Francisca Valeria Fernandes Vieira'),
  ('Gabriela Rocha Marques'),
  ('Gabriela Silveira Teixeira Dantas Mathias'),
  ('Geane Regina Fernandes Costa'),
  ('Hanna Andrade Silva Dias'),
  ('Haroldo Oliveira de Freitas Jr.'),
  ('Iale Oliveira da Hora'),
  ('Isabela Pilar Moraes Alves de Souza'),
  ('José Gabriel de Freitas Silva Benevides'),
  ('José Iuri Martins Bezerra'),
  ('Júlia Maira Ferreira Pereira'),
  ('Karine Adaes Cajado'),
  ('Karla Ramos Melo Oliveira'),
  ('Letícia Andrade'),
  ('Marcelo Montanha Nunes'),
  ('Lucas Barrocas Laranjeira'),
  ('Luiza Caroline Guedes Cardoso'),
  ('Marcos Roberto Andrade Costa Barros'),
  ('Maria Isabel Ribeiro Teles de Aguiar'),
  ('Marina Soares Blanco Gonçalves'),
  ('Patrícia Gomes de Farias'),
  ('Patricia Mamede Carvalho de Miranda'),
  ('Pedro Augusto Nunes de Argollo'),
  ('Quézia Juliana Souza Moreira'),
  ('Rafaela Mendonça Leal'),
  ('Renata Travassos de Oliveira Meirelles'),
  ('Taíssa de Oliveira Paseres'),
  ('Thaise Gordiano Machado'),
  ('Thiago de Faria Junqueira'),
  ('Victor Santos de Almeida'),
  ('Victor Tinôco Vaz Almeida'),
  ('Juliana Vieira Pinto Travassos'),
  ('Luiza Batinga Mascarenhas'),
  ('Marília Maniçoba Amorim de Oliveira')
ON CONFLICT DO NOTHING;